[package]
name = "claid"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = ">=0", features = ["json", "multipart"] }
serde = { version = ">=0", features = ["derive"] }
serde_json = ">=0"
tokio = { version = ">=0" }
